src/ePonto.Web/Models/ErrorViewModel.cs
namespace ePonto.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/ePonto.Web/Models/MarcacaoPontoFormModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace ePonto.Models;

public class MarcacaoPontoFormModel
{
    [DisplayName("Data/Hora")]
    [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
    public DateTime? DataHora { get; set; }

    [DisplayName("Observação")]
    public string? Observacao { get; set; }
}

src/ePonto.Web/Models/MarcacaoPontoViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace ePonto.Models;

public class MarcacaoPontoViewModel
{
    [BindProperty]
    public MarcacaoPontoFormModel Ponto { get; set; }
}

src/ePonto.Web/Models/PontosViewModel.cs
using ePonto.Features.ConsultaPontos;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace ePonto.Models;

public class PontosViewModel
{
    [BindProperty(SupportsGet = true)]
    public DateTime? DataHora { get; set; }

    [MinLength(3)]
    [MaxLength(255)]
    [BindProperty(SupportsGet = true)]
    public string? Observacao { get; set; }

    public IList<Ponto> Pontos { get; set; } = default!;
}

src/ePonto.Web/Controllers/HomeController.cs
using ePonto.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ePonto.Controllers;

[Authorize]
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [AllowAnonymous]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/ePonto.Web/Controllers/PontosController.cs
using ePonto.Features.ConsultaPontos;
using ePonto.Features.MarcacaoPontos;
using ePonto.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;

namespace ePonto.Controllers;

public class PontosController : Controller
{
    private readonly ConsultaPontosInterface _consultaPontosInterface;
    private readonly MarcacaoPontoInterface _marcacaoPontoInterface;

    public PontosController(
        ConsultaPontosInterface consultaPontosInterface,
        MarcacaoPontoInterface marcacaoPontoInterface)
    {
        _consultaPontosInterface = consultaPontosInterface;
        _marcacaoPontoInterface = marcacaoPontoInterface;
    }

    // GET: PontosController
    public async Task<ActionResult<PontosViewModel>> Index()
    {
        var request = new ConsultaPontosRequest();

        var response = await _consultaPontosInterface.ConsultaPontos(request);

        var model = new PontosViewModel();

        model.Pontos = response.Pontos;

        var result = View(model);

        return await Task.FromResult(result);
    }

    // GET: PontosController/Details/5
    public ActionResult Details(int id)
    {
        return View();
    }

    // GET: PontosController/Create
    public async Task<ActionResult<MarcacaoPontoViewModel>> MarcacaoPonto()
    {
        var model = new MarcacaoPontoViewModel();

        var result = View(model);

        return await Task.FromResult(result);
    }

    // POST: PontosController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Marcar(MarcacaoPontoFormModel model)
    {
        try
        {
            var request = new MarcacaoPontoRequest();

            var response = await _marcacaoPontoInterface.MarcaPonto(request);

            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }

    // GET: PontosController/Edit/5
    public ActionResult Edit(int id)
    {
        return View();
    }

    // POST: PontosController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }

    // GET: PontosController/Delete/5
    public ActionResult Delete(int id)
    {
        return View();
    }

    // POST: PontosController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }
}

src/ePonto.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/ePonto.Web/Views/Pontos/Index.cshtml
@model PontosViewModel

@{
    ViewData["Title"] = "Registro de Pontos";
}

<div class="btn-toolbar mb-3" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group me-2" role="group" aria-label="First group">
        <a class="btn btn-primary Criacao Ponto" asp-action="MarcacaoPonto" target="_modal">
            <i class="bi bi-check2-circle"></i>
            Marcar Ponto
        </a>
        @* <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false" data-bs-reference="parent">
        <span class="visually-hidden">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
        <li>
        <a class="dropdown-item Marcacao Ponto" asp-action="Marcar" target="_modal">
        <i class="bi bi-check2-circle"></i>
        Marcar Ponto
        </a>
        </li>
        </ul> *@
    </div>
    @* <div class="btn-group" role="group" aria-label="Second group">
    <a class="btn btn-outline-secondary" asp-action="Comprovantes/Index">Comprovantes</a>
    </div> *@
</div>

<form class="table-responsive text-nowrap" method="get">
    <table class="table table-striped align-middle mb-3 Pontos">
        <thead>
            <tr>
                <th scope="col">Ações</th>
                @* <th scope="col">
                @Html.DisplayNameFor(model => model.Pontos[0].Contrato)
                </th> *@
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Pontos[0].DataHora)
                    <i class="bi bi-sort-down"></i>
                </th>
                @* <th scope="col">
                @Html.DisplayNameFor(model => model.Pontos[0].MomentoId)
                </th>
                <th scope="col">
                @Html.DisplayNameFor(model => model.Pontos[0].PausaId)
                </th>
                <th scope="col">
                @Html.DisplayNameFor(model => model.Pontos[0].Estimado)
                </th> *@
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Pontos[0].Observacao)
                </th>
            </tr>
            <tr>
                <th>
                    <div class="btn-group" role="group">
                        <button type="submit" value="Filtrar" class="btn btn-secondary">
                            <i class="bi bi-funnel"></i>
                            Filtrar
                        </button>
                        <a class="btn btn-warning" asp-action="Index">
                            <i class="bi bi-x-circle"></i>
                        </a>
                    </div>
                </th>
                @* <th>
                <select asp-for="ContratoId" class="form-select" asp-items="ViewBag.ContratoId"></select>
                </th> *@
                <th>
                    <input asp-for="DataHora" class="form-control" />
                </th>
                @* <th>
                <select asp-for="Momento" class="form-select" asp-items="Html.GetEnumSelectListWithEmptyValue<MomentoEnum>()"></select>
                </th>
                <th>
                <select asp-for="Pausa" class="form-select" asp-items="Html.GetEnumSelectListWithEmptyValue<PausaEnum>()"></select>
                </th>
                <th>
                <select asp-for="Estimado" class="form-select">
                <option value=""></option>
                <option value="true">Sim</option>
                <option value="false">Não</option>
                </select>
                </th> *@
                <th>
                    <input asp-for="Observacao" class="form-control" />
                </th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach (var item in Model.Pontos)
        {
            <tr>
                    <td class="p-1" scope="row">
                        <div class="btn-group" role="group">
                            @* <a class="btn btn-link rounded-0" asp-action="./Detalhar" asp-route-id="@item.Id" title="Detalhar">
                        <i class="bi bi-card-text"></i>
                        </a>
                        <a class="btn btn-link Edicao" asp-action="./Editar" asp-route-id="@item.Id" title="Editar" target="_modal">
                        <i class="bi bi-pencil"></i>
                        </a>
                        <a class="btn btn-link text-danger rounded-0 Exclusao" asp-action="./Excluir" asp-route-id="@item.Id" title="Excluir" target="_modal">
                        <i class="bi bi-trash"></i>
                        </a> *@
                        </div>
                    </td>
                    @* <td>
                <a class="text-decoration-none" asp-action="/Contratos/Detalhar" asp-route-id="@item.ContratoId" title="Detalhar" target="_blank">
                @Html.DisplayFor(modelItem => item.Contrato.Nome)
                <i class="bi bi-link-45deg"></i>
                </a>
                </td> *@
                    <td>
                        @Html.DisplayFor(modelItem => item.DataHora)
                    </td>
                    @* <td>
                @Html.DisplayFor(modelItem => item.MomentoId)
                </td>
                <td>
                @Html.DisplayFor(modelItem => item.PausaId)
                </td>
                <td>
                @Html.DisplayFor(modelItem => item.Estimado)
                </td> *@
                    <td>
                        @Html.DisplayFor(modelItem => item.Observacao)
                    </td>
                </tr>
        }
        </tbody>
    </table>
    @* <partial name="_Pagination" model="Model.Pagination" /> *@
</form>

src/ePonto.Web/Views/Pontos/MarcacaoPonto.cshtml
@model MarcacaoPontoViewModel
@{
    ViewData["Title"] = "Marcar Ponto";
}

<form method="post" action="Marcar">
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page">
                        <i class="bi bi-check2-circle"></i>
                        Marcar Ponto
                    </a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row mb-3">
                <label asp-for="Ponto.DataHora" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Ponto.DataHora" class="form-control" readonly />
                    <span asp-validation-for="Ponto.DataHora" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label asp-for="Ponto.Observacao" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <textarea asp-for="Ponto.Observacao" class="form-control"></textarea>
                    <span asp-validation-for="Ponto.Observacao" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="card-footer">
            @Html.AntiForgeryToken()
            <button type="submit" value="Marcar" class="btn btn-primary">
                Marcar
            </button>
        </div>
    </div>
</form>




@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/ePonto.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ePonto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ePonto.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ePonto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pontos" asp-action="Index">Pontos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ePonto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>